### PR TITLE
Adds progress reporting to transfers.

### PR DESCRIPTION
**Pull request by ryanmcgrath**
- Sending and Receiving (the latter via `accept()`) now accept a
  callback parameter for progress reporting, in the form of an
  `FnMut(u64, u64)`. The first parameter is the amount sent/received,
  the latter is the total.

- `bin/main.rs` is updated to implement a terminal progress bar, similar
  to pull request #112 from @moaz-mokhtar.

- Tests updated.

Happy to update if there's a preferred way to handle this, but it works well for me (both in the `bin` example, and my GUI work).

### CODE REVIEW

**Comment by moaz-mokhtar** [comment]
Actually I'm happy and very thankful...
I will do a test in my local copy and enjoy it.

**Comment by piegamesde** [comment]
Thank you. The result is not pretty, but that's okay – it's the API that matters. Please apply `cargo +nightly fmt`. You'll need to rebase on master for this if you're on the latest Rust version.

**Comment by ryanmcgrath** [comment]
Cleaned this up and briefly looked into why the tests are failing on this, but offhand unsure why. Testing the actual binary (`bin/main.rs`) works fine for me, though. Lemme know if there's something I'm missing here?

**Comment by piegamesde** [comment]
The current test situation is a mess, I know. You didn't break them, they were brittle to begin with and it was some subtle change that broke them (it's been a while, I don't remember, but maybe the nonce checking thing?). The whole test suite *badly* needs some love and an overhaul.

In the meantime, we're bound to manual testing. If sending and receiving work for both Rust and Python implementations, that's good enough for now (I'll probably test it tomorrow, but no promises).

**Comment by ryanmcgrath** [comment]
Ah, yeah then - my tests go between a server of mine (Linux/Python) and my main machine (macOS/Rust). Send and receive across both with no issues.

**Pull request merged**
